# Generated by Django 4.0.6 on 2022-07-10 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lektor', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Индивидуальное домашнее задание', 'ИДЗ'), ('Лабораторная работа', 'Л/Р'), ('Курсовая работа', 'КР'), ('Контрольная работа', 'К/Р')], max_length=150, unique=True, verbose_name='тип товара')),
            ],
            options={
                'verbose_name': 'вид деятельности',
                'verbose_name_plural': 'виды деятельности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='unitems.discipline', verbose_name='дисциплина')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='unitems.type', verbose_name='вид работы')),
            ],
        ),
    ]
