# Generated by Django 4.0.6 on 2022-07-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='consultation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Консультация'),
        ),
    ]
