# Generated by Django 4.0.6 on 2022-07-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='lektor',
            field=models.CharField(max_length=200, null=True, verbose_name='ФИО преподавателя'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование дисциплины'),
        ),
    ]
