# Generated by Django 4.0.6 on 2022-07-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('ИДЗ', 'Индивидуальное домашнее задание'), ('Л/Р', 'Лабораторная работа'), ('лекции', 'Лекции'), ('курсач', 'КР'), ('К/Р', 'контрольная')], max_length=150, unique=True, verbose_name='тип товара'),
        ),
    ]
