# Generated by Django 4.0.6 on 2022-07-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unitems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='file',
            new_name='doc',
        ),
    ]
