# Generated by Django 4.0.6 on 2022-07-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitems', '0002_alter_discipline_lektor_alter_discipline_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=1, upload_to='work/'),
            preserve_default=False,
        ),
    ]
