# Generated by Django 4.0.6 on 2022-07-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitems', '0003_product_price_alter_purchace_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchace',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Стоимость'),
        ),
    ]
