# Generated by Django 4.0.6 on 2022-07-12 12:35

from django.db import migrations, models
import django.db.models.deletion
import unitems.models


class Migration(migrations.Migration):

    dependencies = [
        ('unitems', '0004_alter_file_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=unitems.models.user_directory_path)),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterField(
            model_name='discipline',
            name='lektor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО преподавателя'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='product',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='unitems.discipline', verbose_name='дисциплина'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='unitems.type', verbose_name='вид работы'),
        ),
    ]
