# Generated by Django 4.0.6 on 2022-07-12 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_id_user_alter_student_first_name_and_more'),
        ('unitems', '0005_product_alter_discipline_lektor_delete_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaces', to='students.student')),
                ('item', models.ManyToManyField(related_name='purchaces', to='unitems.product')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
    ]
