# Generated by Django 4.0.6 on 2022-07-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitems', '0005_alter_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchace',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Стоимость'),
        ),
    ]
