# Generated by Django 4.0.6 on 2022-07-12 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('unitems', '0006_purchace'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchace',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Стоимость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchace',
            name='purchase_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время покупки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchace',
            name='successful',
            field=models.BooleanField(default=False, verbose_name='Состояние покупки'),
        ),
    ]
