# Generated by Django 4.0.6 on 2022-07-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_user', models.BigIntegerField(unique=True, verbose_name='ID пользователя Telegram')),
                ('username', models.CharField(default='', max_length=250, null=True, verbose_name='Nickname пользователя')),
                ('first_name', models.CharField(default='', max_length=150, null=True)),
                ('last_name', models.CharField(default='', max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ('-id',),
            },
        ),
    ]
